services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    networks:
      - app_network

  shiny:
    build:
      context: ./shiny
    ports:
      - "3838:3838"
    networks:
      - app_network
    depends_on:
      - api

networks:
  app_network:
    driver: bridge